### ------------------------------------------------------------------------------------------------
##  @filename  .travis.yml
##  @author  brikcss  <https://github.com/brikcss>
##  @description  Configuration for Travis CI.
### ------------------------------------------------------------------------------------------------

language: node_js
node_js: '8'

cache:
  bundler: true
  # directories:
  #   - node_modules

notifications:
  email:
    on_failure: always

env: NODE_ENV=test

before_script: npm prune -d
script: npm test -d
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
