### ------------------------------------------------------------------------------------------------
##  @filename  .travis.yml
##  @author  brikcss  <https://github.com/brikcss>
##  @description  Configuration for Travis CI.
### ------------------------------------------------------------------------------------------------

language: node_js
cache:
  bundler: true
  directories:
    - node_modules
notifications:
  email:
    on_failure: always
env: BUILD_LEADER_ID=1 NODE_ENV=test

jobs:
  include:
    - stage: Test on node 8
      node_js: '8'
      before_script: npm prune -d
      script: npm run test -d
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
branches:
  only:
    - master
